"use client";

import { toast } from "sonner"
import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "./ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { GroupedProduct } from "@/app/(inventory)/page";

interface EditInventoryDialogProps {
  product: GroupedProduct;
  setIsEditInventoryOpen: (isOpen: boolean) => void;
}

//poppo code generated by ai probably
export default function EditInventoryDialog({
  product: { modelName, color, sizes },
  setIsEditInventoryOpen
}: EditInventoryDialogProps) {
  const router = useRouter();
  const [quantities, setQuantities] = useState<Record<string, number>>(() => {
    const initial: Record<string, number> = {};
    sizes.forEach((s) => {
      initial[s.inventoryId] = s.quantity;
    });
    return initial;
  });
  const [isSaving, setIsSaving] = useState(false);

  const handleQuantityChange = (inventoryId: string, value: string) => {
    const numValue = parseInt(value, 10);
    if (!isNaN(numValue) && numValue >= 0) {
      setQuantities((prev) => ({ ...prev, [inventoryId]: numValue }));
    } else if (value === "") {
      setQuantities((prev) => ({ ...prev, [inventoryId]: 0 }));
    }
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const updates = sizes.map(async (size) => {
        const newQuantity = quantities[size.inventoryId];
        if (newQuantity !== size.quantity) {
          const response = await fetch(`/api/inventory/${size.inventoryId}`, {
            method: "PATCH",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              action: "update",
              quantity: newQuantity,
            }),
          });
          if (!response.ok) {
            throw new Error(`Failed to update ${size.size}`);
          }
          return response.json();
        }
      });

      await Promise.all(updates);
      toast.success("Quantities updated successfully");
      setIsEditInventoryOpen(false)
      router.refresh(); // Refresh the page data without full reload
    } catch (error) {
      console.error("Failed to update quantities:", error);
      toast.error("Failed to update quantities. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => {
    // Reset quantities to original values
    const original: Record<string, number> = {};
    sizes.forEach((s) => {
      original[s.inventoryId] = s.quantity;
    });
    setQuantities(original);
    setIsEditInventoryOpen(false)
  };

  return (
    <DialogContent
    className="w-full max-w-full sm:max-w-xl transition-all duration-300 max-h-[80vh] overflow-y-auto overflow-x-hidden px-2 md:p-6"
    style={{ boxSizing: "border-box" }}
    onClick={(e) => e.stopPropagation()}
  >
    <DialogHeader>
      <DialogTitle>Edit Inventory</DialogTitle>
      <DialogDescription>
        Update quantities for {modelName} - {color}
      </DialogDescription>
    </DialogHeader>
    <div className="w-full space-y-4 mt-4">
      {sizes.map((size) => (
        <div
          key={size.inventoryId}
          className="flex items-center justify-between gap-4 p-3 border rounded-md"
        >
          <Label htmlFor={`qty-${size.inventoryId}`} className="font-medium">
            Size {size.size}
          </Label>
          <div className="flex items-center gap-2">
            <Input
              id={`qty-${size.inventoryId}`}
              type="number"
              min="0"
              value={quantities[size.inventoryId]}
              onChange={(e) =>
                handleQuantityChange(size.inventoryId, e.target.value)
              }
              className="w-20"
              onClick={(e) => e.stopPropagation()}
            />
          </div>
        </div>
      ))}
      <div className="flex justify-end gap-2 mt-6">
        <Button
          variant="outline"
          onClick={handleCancel}
          disabled={isSaving}
        >
          Cancel
        </Button>
        <Button onClick={handleSave} disabled={isSaving}>
          {isSaving ? "Saving..." : "Save Changes"}
        </Button>
      </div>
    </div>
  </DialogContent>
  );
}
